# The URL the site will be built for
base_url = "https://manank20.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

theme="DeepThought"
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

render_emoji = true



[extra]
# Put all your custom variables here
navbar_items = [
{ code = "en", nav_items = [
    { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/blog", name = "Posts" },
        { url = "$BASE_URL/tags", name = "Tags" },
        { url = "$BASE_URL/categories", name = "Categories" },
] },
]

[extra.author]
name="Manank Patel"
avatar="/images/avatar.png"

[extra.social]
email="manank@gmx.com"
linkedin="manank20"
github="manank20"
gitlab="manank20"
twitter="Manankpatel_20"
reddit="manank_p"
instagram="manank_p"
mastodon_username="manank"
mastodon_server="discuss.systems"
